version: '2'

services:
  dev:
    build: .
    command: sudo npm run dev
    ports:
      - 8088:8088
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
  production:
    build: .
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      NODE_ENV: production
